# Generated by Django 3.2.8 on 2021-10-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='toa.event')),
                ('registrationuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='toa.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='eventcreator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='toa.user'),
            preserve_default=False,
        ),
    ]
