# Generated by Django 3.2.8 on 2021-10-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toa', '0002_auto_20211020_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
