# Generated by Django 3.2.8 on 2021-10-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toa', '0003_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventimage',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
